name = "ecopro-admin-api"
main = "src/index.js"
compatibility_date = "2024-09-01"

[vars]
ALLOWED_ORIGIN = "https://ecopro.keelanodoherty.org"

[[kv_namespaces]]
binding = "ADMIN_KV"
id = "845fa7aabbe34453b52936583bfa0f8f"
